import { useRouter } from "next/router";
import { useEffect, useRef, useState } from "react";
import { doc, getDoc } from "firebase/firestore";
import { db } from "../../lib/firebase";
import { updateOrder } from "../../lib/firestoreHelpers";
import { useAuth } from "../../context/AuthContext";
import { chargeForUsage, getRatePerMinute } from "../../lib/walletHelpers";

const FIELDS = [
  { key: "outerDiameter", label: "قطر بیرونی انگشتر (mm)", shot: "top" },
    { key: "innerDiameter", label: "قطر داخلی / سایز انگشتر (mm)", shot: "top" },
      { key: "bandWidth", label: "عرض بند (mm)", shot: "side" },
        { key: "bandThickness", label: "ضخامت فلز بند (mm)", shot: "inner" },
          { key: "stoneHeight", label: "ارتفاع نگین/طرح از سطح بند (mm)", shot: "detail" },
          ];

          export default function Measure() {
            const router = useRouter();
              const { id } = router.query;
                const { user } = useAuth();
                const [order, setOrder] = useState(null);
                  const [activeShot, setActiveShot] = useState("top");
                    const [refLenMm, setRefLenMm] = useState(20);
                      const [points, setPoints] = useState([]);
                        const [scale, setScale] = useState(null);
                          const [values, setValues] = useState({});
                            const [rate, setRate] = useState(500);
                            const [saving, setSaving] = useState(false);
                            const canvasRef = useRef(null);
                              const imgRef = useRef(null);
                              const startTimeRef = useRef(Date.now());

                                useEffect(() => {
                                    if (!id) return;
                                        getDoc(doc(db, "orders", id)).then(snap => setOrder({ id: snap.id, ...snap.data() }));
                                          }, [id]);

                                            useEffect(() => {
                                                getRatePerMinute().then(setRate);
                                                  }, []);

                                            const drawImage = (url) => {
                                                const canvas = canvasRef.current;
                                                    const ctx = canvas.getContext("2d");
                                                        const img = new Image();
                                                            img.crossOrigin = "anonymous";
                                                                img.onload = () => {
                                                                      const scaleFit = Math.min(canvas.width / img.width, canvas.height / img.height);
                                                                            canvas.dataset.imgW = img.width * scaleFit;
                                                                                  canvas.dataset.imgH = img.height * scaleFit;
                                                                                        ctx.clearRect(0, 0, canvas.width, canvas.height);
                                                                                              ctx.drawImage(img, 0, 0, img.width * scaleFit, img.height * scaleFit);
                                                                                                    imgRef.current = img;
                                                                                                        };
                                                                                                            img.src = url;
                                                                                                              };
                                                                                                              
                                                                                                                useEffect(() => {
                                                                                                                    if (!order) return;
                                                                                                                        const shot = order.photos?.find(p => p.label === activeShot);
                                                                                                                            if (shot) drawImage(shot.url);
                                                                                                                                setPoints([]);
                                                                                                                                  }, [order, activeShot]);
                                                                                                                                  
                                                                                                                                    const handleCanvasClick = (e) => {
                                                                                                                                        const rect = canvasRef.current.getBoundingClientRect();
                                                                                                                                            const x = e.clientX - rect.left;
                                                                                                                                                const y = e.clientY - rect.top;
                                                                                                                                                    const newPoints = [...points, { x, y }];
                                                                                                                                                        setPoints(newPoints);
                                                                                                                                                            redrawPoints(newPoints);
                                                                                                                                                              };
                                                                                                                                                              
                                                                                                                                                                const redrawPoints = (pts) => {
                                                                                                                                                                    const canvas = canvasRef.current;
                                                                                                                                                                        const ctx = canvas.getContext("2d");
                                                                                                                                                                            ctx.clearRect(0, 0, canvas.width, canvas.height);
                                                                                                                                                                                if (imgRef.current) {
                                                                                                                                                                                      const scaleFit = Math.min(canvas.width / imgRef.current.width, canvas.height / imgRef.current.height);
                                                                                                                                                                                            ctx.drawImage(imgRef.current, 0, 0, imgRef.current.width * scaleFit, imgRef.current.height * scaleFit);
                                                                                                                                                                                                }
                                                                                                                                                                                                    ctx.fillStyle = "#c9a24b";
                                                                                                                                                                                                        pts.forEach(p => { ctx.beginPath(); ctx.arc(p.x, p.y, 5, 0, Math.PI * 2); ctx.fill(); });
                                                                                                                                                                                                            if (pts.length === 2) {
                                                                                                                                                                                                                  ctx.strokeStyle = "#c9a24b"; ctx.lineWidth = 2;
                                                                                                                                                                                                                        ctx.beginPath(); ctx.moveTo(pts[0].x, pts[0].y); ctx.lineTo(pts[1].x, pts[1].y); ctx.stroke();
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                              };
                                                                                                                                                                                                                              
                                                                                                                                                                                                                                const pxDist = (a, b) => Math.hypot(a.x - b.x, a.y - b.y);
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                  const calibrate = () => {
                                                                                                                                                                                                                                      if (points.length !== 2) { alert("دو نقطه‌ی ابتدا و انتهای مرجع اندازه رو لمس کن."); return; }
                                                                                                                                                                                                                                          const px = pxDist(points[0], points[1]);
                                                                                                                                                                                                                                              setScale(refLenMm / px);
                                                                                                                                                                                                                                                  setPoints([]);
                                                                                                                                                                                                                                                      redrawPoints([]);
                                                                                                                                                                                                                                                          alert(`کالیبره شد: هر پیکسل = ${(refLenMm / px).toFixed(4)} میلی‌متر`);
                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                              const measureField = (key) => {
                                                                                                                                                                                                                                                                  if (!scale) { alert("اول باید روی همین عکس کالیبراسیون انجام بشه."); return; }
                                                                                                                                                                                                                                                                      if (points.length !== 2) { alert("دو نقطه‌ی ابتدا و انتهای اندازه موردنظر رو لمس کن."); return; }
                                                                                                                                                                                                                                                                          const px = pxDist(points[0], points[1]);
                                                                                                                                                                                                                                                                              const mm = (px * scale).toFixed(2);
                                                                                                                                                                                                                                                                                  setValues(v => ({ ...v, [key]: mm }));
                                                                                                                                                                                                                                                                                      setPoints([]);
                                                                                                                                                                                                                                                                                          redrawPoints([]);
                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                              const saveAndContinue = async () => {
                                                                                                                                                                                                                                                                                                  setSaving(true);
                                                                                                                                                                                                                                                                                                  const durationMs = Date.now() - startTimeRef.current;
                                                                                                                                                                                                                                                                                                  const result = await chargeForUsage(user.uid, id, durationMs);
                                                                                                                                                                                                                                                                                                  if (!result.ok) {
                                                                                                                                                                                                                                                                                                      setSaving(false);
                                                                                                                                                                                                                                                                                                      alert(`موجودی کیف پول کافی نیست. هزینه‌ی این اندازه‌گیری ${result.cost.toLocaleString("fa-IR")} تومانه ولی موجودیت ${result.balance.toLocaleString("fa-IR")} تومانه. اول کیف پولت رو شارژ کن.`);
                                                                                                                                                                                                                                                                                                      router.push("/wallet");
                                                                                                                                                                                                                                                                                                      return;
                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                  await updateOrder(id, { measurements: values, status: "measured" });
                                                                                                                                                                                                                                                                                                      router.push(`/result/${id}`);
                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                          if (!order || !user) return null;
                                                                                                                                                                                                                                                                                                            const shots = [...new Set(order.photos?.map(p => p.label))];
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                  <div className="container">
                                                                                                                                                                                                                                                                                                                        <h2 style={{ marginTop: 20 }}>اندازه‌گیری روی عکس</h2>

                                                                                                                                                                                                                                                                                                                        <div className="card">
                                                                                                                                                                                                                                                                                                                          <b>این مرحله چطور کار می‌کنه؟</b>
                                                                                                                                                                                                                                                                                                                          <p style={{ fontSize: 13, color: "#9aa4b8", marginTop: 6, lineHeight: 2 }}>
                                                                                                                                                                                                                                                                                                                            چون عکس‌ها مقیاس واقعی ندارن، اول باید به اپ بگی «این فاصله روی عکس چند میلی‌متر واقعیه؟» — یعنی کالیبراسیون. دو سر مرجع اندازه (مثلاً لبه‌های سکه) رو لمس کن، طولش رو وارد کن و کالیبره بزن. بعد برای هر اندازه‌ای که می‌خوای، دو نقطه‌ی ابتدا و انتهاش رو لمس کن و «ثبت» بزن؛ اپ خودش میلی‌متر واقعی رو حساب می‌کنه.
                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                              <div className="card">
                                                                                                                                                                                                                                                                                                                                      <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginBottom: 10 }}>
                                                                                                                                                                                                                                                                                                                                                {shots.map(s => (
                                                                                                                                                                                                                                                                                                                                                            <button key={s} className={`btn ${activeShot === s ? "" : "secondary"}`} onClick={() => { setActiveShot(s); setScale(null); }}>
                                                                                                                                                                                                                                                                                                                                                                          {s}
                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                <canvas ref={canvasRef} width={340} height={340} style={{ background: "#000", borderRadius: 8, width: "100%", touchAction: "none" }} onClick={handleCanvasClick} />
                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="card">
                                                                                                                                                                                                                                                                                                                                                                                                                                    <b>۱. کالیبراسیون</b>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <p style={{ fontSize: 13, color: "#9aa4b8" }}>دو سر مرجع اندازه (سکه/خط‌کش) رو روی عکس لمس کن، طول واقعی‌ش رو وارد کن و کالیبره بزن.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label>طول واقعی مرجع (mm)</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input type="number" value={refLenMm} onChange={e => setRefLenMm(Number(e.target.value))} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button className="btn" style={{ marginTop: 10 }} onClick={calibrate}>کالیبره کن ({points.length}/2 نقطه)</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {scale && <p style={{ color: "#6fe0a0", fontSize: 13 }}>✓ کالیبره شده: {scale.toFixed(4)} mm/px</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <b>۲. اندازه‌گیری</b>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {FIELDS.filter(f => f.shot === activeShot).map(f => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div key={f.key} style={{ marginTop: 10, display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span style={{ fontSize: 14 }}>{f.label} {values[f.key] && <b style={{ color: "#c9a24b" }}>= {values[f.key]}mm</b>}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button className="btn secondary" onClick={() => measureField(f.key)}>ثبت ({points.length}/2)</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p style={{ fontSize: 12, color: "#8a93a8", textAlign: "center" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                هزینه‌ی استفاده از این ابزار، بر اساس مدت زمانی که صرف می‌کنی ({rate.toLocaleString("fa-IR")} تومان/دقیقه)، موقع ذخیره از کیف پولت کسر می‌شه.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button className="btn" style={{ width: "100%" }} disabled={saving} onClick={saveAndContinue}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {saving ? "در حال ثبت..." : "ذخیره و مشاهده نتیجه نهایی"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
